name: Build Program on Ubuntu 14.04

on:
  push:
    branches: [ v33 ]
  pull_request:
    branches: [ v33 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build
      run: |
        cd ./js/src/build-win32
        chmod +x build.sh
        sh build.sh