name: Build Program on Ubuntu 14.04

on:
  push:
    branches: [ v33 ]
  pull_request:
    branches: [ v33 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare environment
      run: |
        apt-get update
        apt-get install -y build-essential

    - name: Build
      run: |
        chmod +x ./js/src/build-win32
        sh ./build.sh