name: Build Program on Ubuntu 14.04

on:
  push:
    branches: [ v33 ]
  pull_request:
    branches: [ v33 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Env
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y make
    - name: Build
      run: |
        cd ./js/src/
        autoconf-2.13
        cd build-linux
        ../configure --enable-debug --disable-optimize
        chmod +x build.sh
        sh build.sh